name: Daily Green Square Bot

on:
  schedule:
    # Runs at 12:00 UTC every day. You can change this using crontab syntax.
     - cron: '0 */2 * * *'
  workflow_dispatch: # This allows you to run it manually from the Actions tab

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change to a file
        run: |
          echo "Last run: $(date)" >> daily_log.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "mouneesh798"
          git config --global user.email "mouneeshb123@gmail.com"
          git add daily_log.txt
          git commit -m "Automated daily activity" || exit 0
          git push
